name: Code Quality

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  check_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check code format (Black)
        run: black ezio --check --diff
      - name: Run static code analysis (Pylint)
        run: pylint ezio --disable=C0114,W0718,W0719,R0903,W0613,R0801
